### ISSUE TITLE
역할 분담 및 어플 디자인 결정

### ISSUE THREAD

**Issue by KIMSEIHEE** [kookmin-sw/2018-cap1-3#1]

**Comment by KIMSEIHEE** [comment]
역할 분담 및 어플 디자인 결정

**Comment by Nambyungwook** [comment]
- [앱 기능 구현]

1.  3월 15~16일 구글 캘린더 api 자료조사
2.  3월 16~18일 처음(로딩)화면 - 화면 전환 기능구현
3.  3월 18~20일 메인화면 + 알람추가화면 -  화면전환기능 및 메인화면 각 버튼 기능 구현
4.  3월 20~23일 알람추가화면 -  알람추가기능 및 구글 캘린더 연동 기능 구현
5.  3월 23~25일 캘린더화면 - 월, 일 선택 기능 및 텍스트 추가와 알람앱 내로 자료 전달 기능 구현

**Comment by 20143024** [comment]
앱 UI - KIMSEIHEE
앱 기능 구현 - Nambyungwook (+ 20143024, weegwangjin)
TTS 딥러닝 - weegwangjin (+ 20143024, KIMSEIHEE, Nambyungwook)
서버 - 20143024

**Comment by KIMSEIHEE** [comment]
[회의시간]
월 저녁 / 수 저녁 / 금 오후
하루 3~4시간 조율
